services:
  discovery-service:
    image: mehmetemre46/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - api-gateway
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
  api-gateway:
    image: mehmetemre46/api-gateway
    ports:
      - 8020:8020
    mem_limit: 700m



