services:
  discovery-service:
    image: mehmetemre46/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev

  api-gateway:
    image: mehmetemre46/api-gateway
    ports:
      - 8020:8020
    mem_limit: 700m

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-manager:
    image: hlebalbau/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - /path/to/store/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

  orderservice:
    image: mehmetemre46/orderservice:latest
    ports:
      - 7001:7001
    mem_limit: 700m
    depends_on:
      - postgres
  productservice:
    image: mehmetemre46/productservice:latest
    ports:
      - 6001:6001
    mem_limit: 700m
    depends_on:
      - mongodb
#  mongo:
#    image: mongodb/mongodb-community-server:5.0.2-ubuntu2004
#    container_name: mongodb
#    restart: always
#    volumes:
#      - /C/2023_Kodlama/dockerVolumes/2:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - 27017:27017
#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
##    ports:
##      - 9070:9070
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#    depends_on:
#      - mongo

#  mongo-express:
#    image: mongo-express:latest
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#    depends_on:
#      - mongo