services:
  discovery-service:
    image: mehmetemre46/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - api-gateway
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
  api-gateway:
    image: mehmetemre46/api-gateway
    ports:
      - 8020:8020
    mem_limit: 700m
  mongo:
    image: mongodb/mongodb-community-server:5.0.2-ubuntu2004
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 9070:9070
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
  orderservice:
    image: mehmetemre46/orderservice:latest
    ports:
      - 7001:7001
    mem_limit: 700m
  productservice:
    image: mehmetemre46/productservice:latest
    ports:
      - 6001:6001
    mem_limit: 700m
